---
title: 'Práctica 2'
author: 'Juan Manuel Rivas Castillo'
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    latex_engine: xelatex
header-includes:
  - "\\usepackage{hyperref}"
---

```{r setup, include= FALSE}
library(reticulate)
py_install("sympy")
py_install("numpy")
py_install("statsmodels")
```



**Pregunta 1:**
 
Considerando la siguiente información, obtenga $\beta_1$ y $\beta_2$

$$\mu_1 = 3-\beta_1 - \beta_2$$
$$\mu_1 = 5-\beta_1 - 2\beta_2$$
$$\mu_1 = 6-\beta_1 - 3\beta_2$$

\textbf{Respuesta:}

$$\mu_1^2 + \mu_2^2 + \mu_3^2 =(3-\beta_1 - \beta_2)^2+(5-\beta_1 - 2\beta_2)^2+(6-\beta_1 - 3\beta_2)^2$$
$$ SRC = (3-\beta_1 - \beta_2)^2+(5-\beta_1 - 2\beta_2)^2+(6-\beta_1 - 3\beta_2)^2$$
$$\frac{\partial SRC}{\partial \beta_1}=2(3-\beta_1 - \beta_2)(-1)+2(5-\beta_1 - 2\beta_2)(-1)+2(6-\beta_1 - 3\beta_2)(-1)$$
$$\frac{\partial SRC}{\partial \beta_1}=6 -2\beta_1-2\beta_2+ 10-2\beta_1-4\beta_2+ 12- 2\beta_1-6\beta_2$$
$$\frac{\partial SRC}{\partial \beta_1}=28-6\beta_1-12\beta_2$$

$$\frac{\partial SRC}{\partial \beta_2}=2(3-\beta_1 - \beta_2)(-1)+2(5-\beta_1 - 2\beta_2)(-2)+2(6-\beta_1 - 3\beta_2)(-3)$$

$$\frac{\partial SRC}{\partial \beta_2}=6 -2\beta_1 -2\beta_2 + 20 -4\beta_1 -8\beta_2+36-6\beta_1 -18\beta_2$$

$$\frac{\partial SRC}{\partial \beta_2}= 62-12\beta_1-28\beta_2$$

$$\begin{pmatrix} \beta_1 \\ \beta_2 \end{pmatrix} = \begin{pmatrix} 6 & 12 \\ 12 & 28 \end{pmatrix}^{-1} \begin{pmatrix} 28\\ 62 \end{pmatrix} $$

$$\begin{pmatrix} \beta_1 \\ \beta_2 \end{pmatrix} = \frac{1}{24}\begin{pmatrix} 28 & -12 \\ -12 & 6 \end{pmatrix} \begin{pmatrix} 28\\ 62 \end{pmatrix} $$

$$\beta_1= 1.67; \beta_2=1.50$$

\textbf{Cáculo con Python}

```{python}
#!pip install sympy
from sympy import *
b1 = Symbol('b1')
b2 = Symbol('b2')
SRC = (3-b1-b2)**2 + (5-b1-2*b2)**2 +(6-b1-3*b2)**2
r1 = diff(SRC,b1)
r2 = diff(SRC,b2)
print(solve([r1,r2],[b1,b2]))
```
\textbf{Cálculo de los valores predichos de Y}

```{python}
Y1 = 5/3 + 3/2
Y2 = 5/3 + 2*3/2
Y3 = 5/3 + 3*3/2
print("Y1 =", round(Y1,2), "Y2=", round(Y2,2), "Y3=", round(Y3,2))
```

**Pregunta 2:**
Partiendo una muestra de 200 observaciones se obtuvieron los siguientes resultados:

$\sum X = 11.34$,  $\sum Y = 20.72$, $\sum X^2 = 12.16$, $\sum Y^2 = 84.96$, $\sum XY= 22.13$.

Estimar los coeficientes del modelo así como su varianza 

\textbf{Obtención de coeficientes}

$$\begin{pmatrix} \alpha \\ \beta \end{pmatrix}= \begin{pmatrix} 200 & 11.34 \\ 11.34 & 12.16 \end{pmatrix}^{-1} \begin{pmatrix} 20.72 \\ 22.13 \end{pmatrix}$$

$$\begin{pmatrix} \alpha \\ \beta \end{pmatrix}= \frac{1}{2303.404}\begin{pmatrix} 12.16  & -11.34 \\ -11.34 & 200 \end{pmatrix} \begin{pmatrix} 20.72 \\ 22.13 \end{pmatrix}$$

$$\alpha = 0.0004345742,  \beta=1.82$$

\textbf{Obtención de la varianza de los coeficientes}

Podemos usar el hecho que la STC es $\sigma^2_y = \sum y^2- n \overline{y}^2 = 84.96-200(\frac{20.72}{200})^2=82.81$

Mientras que la SEC es  $\beta^2\sigma^2_X = \beta^2(\sum X^2- n \overline{X}^2) = 1.82^2(12.16- 200(\frac{11.34}{200})^2)= 38.15$

$\rightarrow$ SRC= 44.66 $\rightarrow$ $\sigma^2_{\mu}= 0.23$

$$\sigma^2_{\beta} = 0.23*\begin{pmatrix} \frac{12.16}{2303.404}  & \frac{-11.34}{2303.404} \\ \frac{-11.34}{2303.404}  & \frac{200}{2303.404}  \end{pmatrix} $$

\textbf{Código en Python}

```{python import}
#!pip install numpy statsmodels
import numpy as np
import statsmodels.api as sm
```

```{python, test}
XtX = np.array([[200,11.34],[11.34,12.16]])
XtY = np.array([[20.72],[22.13]])
B =  np.dot(np.linalg.inv(XtX),XtY)
print(B)

```

\textbf{Código en R}

```{R}
XtX = matrix(c(200, 11.34, 11.34,12.16), nrow=2, byrow=TRUE)
XtY = matrix(c(20.72,22.13), nrow=2)
B = solve(XtX)%*%XtY
print(B)
```
**Pregunta 3:**

 En una muestra de leche de un cierto número de vacas lecheras correspondiente a dos rebaños se midio el porcentaje de grasas (X) y el porcentaje de elementos sólidos no grasos (Y) calcular la ecuación de regresión lineal dada la siguiente información para cada rebaño:

Rebaño 1:

$\sum X = 51.13, \sum Y = 117.25, \sum x^2= 1.27, \sum y^2= 4.78, \sum xy = 1.84$

Número de vacas = 16

Rebaño 2:

$\sum X = 37.20, \sum Y = 78.75, \sum x^2= 1.03, \sum y^2= 2.48, \sum xy = 1.10$

Número de vacas = 10

**Rebaño 1**
$$\beta = 1.84/1.27= 1.45; \quad \alpha = \frac{117.25}{16}-1.45*\frac{51.13}{16}=2.69$$
$$\hat{y} = 2.69 + 1.45*X$$
**Rebaño 2**
$$\beta = 1.10/1.03= 1.07; \quad \alpha = \frac{78.75}{10}-1.07*\frac{37.20}{10}=3.89$$
$$\hat{y} = 3.89 + 1.07*X$$


**Pregunta 4:**

Los datos de producción de 22 empresas de una determinada industria dan lugar a los siguientes resultados:

$\overline{y}=20, \quad  \sum_{i=1}^n(y_i-\overline{y})^2=100$

$\overline{x}=10, \quad \sum_{i=1}^n(x_i-\overline{x})^2=60$ y

$\sum_{i=1}^n(x_i-\overline{x})(y_i-\overline{y})=30$

Donde: y = ln(produccion) y x = ln(horas de trabajo). Con esta información se pide calcular $\alpha$ y $\beta$ a partir de la siguiente especificación $y=\alpha + \beta x + \epsilon$

$$\beta =\frac{30}{60}=0.5; \quad \alpha = 20 -0.5*10 = 15 $$ 
$$\hat{y}= 15 - 0.5 X$$

**Pregunta 5:**

 Sea la siguiente tabla que muestra información de una función de demanda. Se pide que con dicha información calcule los coeficientes del modelo con intercepto y sin intercepto. La especificación con intercepto es : $Q = \alpha + \beta P +\epsilon$. 


| Q | P |  
|---|:--|
|3 | 18 | 
| 3 | 16 |
| 7 | 17 |
| 6 | 12 | 
| 10 | 15 |
| 15 | 15 |
| 16 | 4 |
| 13 | 13 |
| 9 | 11 |
| 15 | 6 |

$$cov(y,x)= -15.77 \quad var(x)= 21.34$$
$$\beta = \frac{-15.77}{19.21}=-0.74$$
$$\alpha = \overline{Y}- \beta\overline{X}=19.08 $$

\textbf{Código en Python}

```{python, test2}
data = np.array([[3,18],[3,16],[7,17],[6,12],[10,15],[15,15],[16,4],[13,13],[9,11],[15,6]])
X=data[:,1]
Y = data[:,0]
sX =sum(X)
mX = np.mean(X)
covYX = np.cov(Y,X)[0][1]
varX= np.cov(Y,X)[1][1]
b = covYX/varX
print(b)
a = np.mean(Y)-b*np.mean(X)
print(a)
X = sm.add_constant(X)
model = sm.OLS(Y, X)
results = model.fit()
results.params[:,None]
```

\textbf{Código en R}

```{R}
X = matrix(c(18,16, 17,12,15,15, 4,13,11,6),nrow=10)
Y = matrix(c(3,3,7,6,10,15,16,13,9,15),nrow=10)
print(cov(Y,X)); print(var(X))
B = cov(Y,X)/var(X)
a = mean(Y)-B*mean(X)
print(a);print(B)

```

**Pregunta 6:**

A partir de los siguientes pares ordenados: $(1,2)$, $(3,6)$, $(8,2.5)$, $(4,1.3)$ y $(0.5,1.6)$ obtenga los estimadores de un modelo de regresión simple.

\textbf{Resultados con Python}
```{python, test3}
X = [1,3,8,4,0.5]
Y = [2,6,2.5,1.3,1.6]
B = np.cov(Y,X)[0][1]/np.var(X)
print(B)
a = np.mean(Y)-B*np.mean(X)
print(a)
X = sm.add_constant(X)
model = sm.OLS(Y, X)
results = model.fit()
results.params[:,None]
```
\textbf{Resultados con R}

```{R}
X = matrix(c(1,3,8,4,0.5),nrow=5)
Y = matrix(c(2,6,2.5,1.3,1.6),nrow=5)
B= cov(X,Y)/var(X)
a = mean(Y)-B*mean(X)
print(a); print(B)
```

**Pregunta 7:** 

Se quiere estimar la relación entre el rendimiento de un vehículo y el peso del mismo, a partir de la siguiente especificación: $Rendimiento = \alpha + \beta Peso + \epsilon$. Para este proceo se cuenta con 74 observaciones y los siguientes datos: $\sum Peso = 223.44$, $\sum Peso^2 = 718.76$, $\sum y = 1576$  y $\sum yx = 4493.72$

$$\begin{pmatrix} \alpha \\ \beta \end{pmatrix} = \begin{pmatrix} 74 & 223.44 \\223.44 & 718.76 \end{pmatrix}^{-1} \begin{pmatrix} 1576 \\ 4493.72 \end{pmatrix}$$
$$\begin{pmatrix} \alpha \\ \beta \end{pmatrix} = \frac{1}{3262.8}\begin{pmatrix} 718.76 & -223.44 \\ -223.44 & 74 \end{pmatrix} \begin{pmatrix} 1576 \\ 4493.72 \end{pmatrix}$$

$\alpha = 39.44 \quad \beta = -6.01$

\textbf{Código en Python}

```{python, test4}
XX = np.array([[74, 223.44],[223.44, 718.76]])
XY = np.array([[1576],[4493.72]])
dXX = np.linalg.det(XX)
alpha = (718.76*1576 -223.44*4493.72)/dXX
beta =  (-223.44*1576 + 74*4493.72)/dXX
print('alpha', {round(alpha,2)}, 'beta', {round(beta,2)})
B = np.dot(np.linalg.inv(XX),XY)
print(B)
```

\textbf{Código en R}

```{R}
XtX = matrix(c(74, 223.44, 223.44, 718.76), nrow=2, byrow=TRUE)
XtY = matrix(c(1576,4493.72),nrow=2)
B = solve(XtX)%*%XtY
print(B)

```